name: Go

on:
  push:
    branches: [ master ]
    tags: ["v*.*.*"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.3

      - name: Build
        run: |
          build() {
            export GOOS=$1
            export GOARCH=$2
            go build -ldflags "-s -w" -o release/rapid-dns-${1}-${2}${3} main.go
          }
          build linux amd64
          build windows amd64 .exe
          build windows 386 .exe
          build darwin amd64
          build darwin arm64
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: release/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
